backend/chat/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'chat'

urlpatterns = [
    path("", index, name="index"),
    path("chat/<str:room_name>/", room, name="room"),
    path("create_group/", create_group, name="create_group"),
    path("register/", register_user, name="register"),
    path('login/', LoginView.as_view(), name='login'),
    path('edit-profile/', edit_profile, name='edit_profile'),
    path('logout/', logout_view, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/messenger_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls', namespace='chat')),
]

backend/chat/models.py
from django.db import models
from django.contrib.auth.models import User


class Message(models.Model):
    author = models.ForeignKey(User, related_name='author_message', on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)


class Group(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to='profile_images/', blank=True, null=True)
    full_name = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.user.username

backend/chat/forms.py
from django import forms
from .models import Group, UserProfile


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_image', 'full_name']

backend/chat/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.models import User

from .forms import GroupForm, UserProfileForm
from .models import Group, UserProfile


def index(request):
    groups = Group.objects.all()
    create_group_url = reverse('chat:create_group')
    users = User.objects.all()  # Получаем всех пользователей из таблицы auth_user

    return render(request, "chat/index.html", {"groups": groups,
                                               "create_group_url": create_group_url,
                                               'users': users
                                               })


def room(request, room_name):
    return render(request, "chat/room.html", {"room_name": room_name})


def create_group(request):
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('chat:index')  # Перенаправляем на страницу index после создания группы
    else:
        form = GroupForm()
    return render(request, 'chat/create_group.html', {'form': form})


def register_user(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('chat:index')
    else:
        form = UserCreationForm()
    return render(request, 'chat/register.html', {'form': form})


@login_required
def edit_profile(request):
    user_profile, created = UserProfile.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = UserProfileForm(instance=user_profile)

    return render(request, 'chat/edit_profile.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('/')

backend/chat/templates/chat/create_group.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Create Group</title>
</head>
<body>
<h2>Create a New Group</h2>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Create Group</button>
</form>

<a href="{% url 'chat:index' %}">Back to Chat Rooms</a>

</body>
</html>

backend/chat/templates/chat/edit_profile.html
<!DOCTYPE html>
<html>
<head>
    <title>Edit Profile</title>
</head>
<body>
    <h2>Edit Profile</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Save</button>
    </form>
</body>
</html>

backend/chat/templates/chat/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
    <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
{% if user.is_authenticated %}
    <h2>Welcome, {{ user.userprofile.full_name }}!</h2>
{% if user.userprofile.profile_image %}
    <img src="{{ user.userprofile.profile_image.url }}" alt="Profile Image" width="100">
{% endif %}

    <a href="/edit-profile/"><button>Edit Profile</button></a>
    <a href="/logout/"><button>Log out</button></a>
    <p></p>
    <h2>All Chat Groups:</h2>
    <ul>
        {% for group in groups %}
        <li><a href="{% url 'chat:room' group.name %}">{{ group.name }}</a></li>
        {% endfor %}
    </ul>
    <a href="{{ create_group_url }}"><button>Create Group</button></a>
{% else %}
    <h2>You are not authenticated.</h2>
    <a href="/register/"><button>Register</button></a>
    <a href="/login/"><button>Log in</button></a>
{% endif %}

<p></p>
<h2>All Users:</h2>
<ul>
    {% for user in users %}
    <li><a href="{% url 'chat:room' user.username %}">{{ user.username }}</a></li>
    {% endfor %}
</ul>
<script></script>
</body>
</html>

backend/chat/templates/chat/register.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Registration</title>
</head>
<body>
<h2>Registration</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>
</body>
</html>

backend/chat/templates/chat/room.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Chat Room</title>
</head>
<body>
<textarea id="chat-log" cols="100" rows="20"></textarea><br>
<input id="chat-message-input" type="text" size="100"><br>
<input id="chat-message-submit" type="button" value="Send">
{{ room_name|json_script:"room-name" }}
<script>
  const roomName = JSON.parse(document.getElementById('room-name').textContent);

  const chatSocket = new WebSocket(
          'ws://'
          + window.location.host
          + '/ws/chat/'
          + roomName
          + '/'
  );

  chatSocket.onmessage = function(e) {
    const data = JSON.parse(e.data);
    document.querySelector('#chat-log').value += (data.message + '\n');
  };

  chatSocket.onclose = function(e) {
    console.error('Chat socket closed unexpectedly');
  };

  document.querySelector('#chat-message-input').focus();
  document.querySelector('#chat-message-input').onkeyup = function(e) {
    if (e.key === 'Enter') {  // enter, return
      document.querySelector('#chat-message-submit').click();
    }
  };

  document.querySelector('#chat-message-submit').onclick = function(e) {
    const messageInputDom = document.querySelector('#chat-message-input');
    const message = messageInputDom.value;
    chatSocket.send(JSON.stringify({
      'message': message
    }));
    messageInputDom.value = '';
  };
</script>
</body>
</html>